NOTICKET: urgent changes

diff --git a/.github/workflows/reusable-ci-cd.yml b/.github/workflows/reusable-ci-cd.yml
--- a/.github/workflows/reusable-ci-cd.yml
+++ b/.github/workflows/reusable-ci-cd.yml
@@ -207,40 +207,40 @@ jobs:
           path: "*.xml"
           retention-days: 30
           if-no-files-found: warn    
-      - name: Set up SonarQube project
-        run: |
-          # Create project and get token
-          PROJECT_KEY="${{ github.event.repository.name }}"
-          # Create project (using default admin credentials)
-          curl -u admin:admin -X POST "http://localhost:9000/api/projects/create?project=${PROJECT_KEY}&name=${PROJECT_KEY}"
-          echo "http://localhost:9000/api/projects/create?project=${PROJECT_KEY}&name=${PROJECT_KEY}"
-
-          # Generate user token for analysis
-          echo  "http://localhost:9000/api/user_tokens/generate?name=github-actions-${GITHUB_RUN_ID}"
-          curl -u admin:admin -X POST "http://localhost:9000/api/user_tokens/generate?name=github-actions" -vvv
-          TOKEN_RESPONSE=$(curl -u admin:admin -X POST "http://localhost:9000/api/user_tokens/generate?name=github-actions-${GITHUB_RUN_ID}")
-          TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.token')
-          echo "SONAR_TOKEN=${TOKEN}"
-          echo "PROJECT_KEY=${PROJECT_KEY}"
-
-          /github/workspace/sonar/bin/sonar-scanner \
-            -Dsonar.projectKey=${PROJECT_KEY} \
-            -Dsonar.sources=. \
-            -Dsonar.host.url=http://localhost:9000 \
-            -Dsonar.login=${TOKEN} \
-            -Dsonar.python.coverage.reportPaths=coverage.xml \
-            -Dsonar.python.xunit.reportPath=test-results.xml \
-            -Dsonar.python.bandit.reportPaths=bandit-report.json \
-            -Dsonar.exclusions=tests/**,venv/**,env/**,**/__pycache__/**
-          sleep 30
-          QUALITY_GATE=$(curl -u ${TOKEN}: "http://localhost:9000/api/qualitygates/project_status?projectKey=${PROJECT_KEY}" | jq -r '.projectStatus.status')
-        
-          echo "Quality Gate Status: $QUALITY_GATE"       
-          if [ "$QUALITY_GATE" != "OK" ]; then
-            echo "Quality Gate failed!"
-            echo "Ignoring errors for now, change next line to 'exit 1' to enforce quality gate."
-            exit 0
-          fi
+#      - name: Set up SonarQube project
+#        run: |
+#          # Create project and get token
+#          PROJECT_KEY="${{ github.event.repository.name }}"
+#          # Create project (using default admin credentials)
+#          curl -u admin:admin -X POST "http://localhost:9000/api/projects/create?project=${PROJECT_KEY}&name=${PROJECT_KEY}"
+#          echo "http://localhost:9000/api/projects/create?project=${PROJECT_KEY}&name=${PROJECT_KEY}"
+#
+#          # Generate user token for analysis
+#          echo  "http://localhost:9000/api/user_tokens/generate?name=github-actions-${GITHUB_RUN_ID}"
+#          curl -u admin:admin -X POST "http://localhost:9000/api/user_tokens/generate?name=github-actions" -vvv
+#          TOKEN_RESPONSE=$(curl -u admin:admin -X POST "http://localhost:9000/api/user_tokens/generate?name=github-actions-${GITHUB_RUN_ID}")
+#          TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.token')
+#          echo "SONAR_TOKEN=${TOKEN}"
+#          echo "PROJECT_KEY=${PROJECT_KEY}"
+#
+#          /github/workspace/sonar/bin/sonar-scanner \
+#            -Dsonar.projectKey=${PROJECT_KEY} \
+#            -Dsonar.sources=. \
+#            -Dsonar.host.url=http://localhost:9000 \
+#            -Dsonar.login=${TOKEN} \
+#            -Dsonar.python.coverage.reportPaths=coverage.xml \
+#            -Dsonar.python.xunit.reportPath=test-results.xml \
+#            -Dsonar.python.bandit.reportPaths=bandit-report.json \
+#            -Dsonar.exclusions=tests/**,venv/**,env/**,**/__pycache__/**
+#          sleep 30
+#          QUALITY_GATE=$(curl -u ${TOKEN}: "http://localhost:9000/api/qualitygates/project_status?projectKey=${PROJECT_KEY}" | jq -r '.projectStatus.status')
+#        
+#          echo "Quality Gate Status: $QUALITY_GATE"       
+#          if [ "$QUALITY_GATE" != "OK" ]; then
+#            echo "Quality Gate failed!"
+#            echo "Ignoring errors for now, change next line to 'exit 1' to enforce quality gate."
+#            exit 0
+#          fi
   deploy:
     needs: [build, pre-build]
     runs-on: [self-hosted]
